version: '3.1'

services:

  ghost:
    image: ghost:alpine
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
