name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.2.0
      with:
        node-version: 14
        cache: 'npm'

    - run: npm ci
    - run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
          cache: 'npm'

      - if: github.ref == 'refs/heads/main'
        run: npm run pack
      - if: github.ref == 'refs/heads/main'
        uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          file: "gillyreads.zip"
